### ISSUE TITLE
ansible module

### ISSUE THREAD

**Issue by jrandall** [wtsi-hgi/gitlab-build-variables-manager#1]
Can this also be packaged as an ansible module so that we can set up the gitlab secret variables from ansible?

**Comment by colin-nolan** [comment]
I'm working on a solution for setting projects secrets: will give update shortly.

**Comment by colin-nolan** [comment]
Implemented in `hgi-systems` module:
https://github.com/wtsi-hgi/hgi-systems/blob/master/ansible/gitlab-projects.yml
